Given a string, draw the PAC, pseudocode and develop the
python code to check whether the given string is a magic string
or not. A string is said to be a magic string if the substrings
formed by characters in the even positions and odd positions are
the same. If the string is of odd length, the middle character has
to be skipped.
For example, the string ‘aabbcc’ is a magic string as the
substring ‘abc’ that is formed using character at even position
and the substring ‘abc’ that is formed using character at odd
position is same. However the string ‘abcabc’ is not a magic
string.


```
Input format:
Enter a string
Output format:
Magic string
Not a magic string
Test Cases Input
aabbcc
abcabc
aabcc
Test Cases Expected Output
Magic string
Not a magic string
Magic string
Test Cases Input aba
Test Cases Expected Output Not a magic string
Test Cases Input aaaabbbbcccc
Test Cases Expected Output Magic string
```

**Input:**
```
str //input String
```
**Logic:-**
Used while loop to test All conditions
```
 if(len(even)!=len(odd)):
        even=even.replace(even[int(len(even)/2)],"") #If the element is odd
                                                replace middle character with ""
    if(even==odd):
        print("Magic string")
    else:
        print("Not a magic string")
```
**OUTPUT:-**
```
Magic String
Not Magic String
```

In [9]:
import math
s=input("Enter String:-") #Input String
while(s!='Stop'):
    even = (s[0:len(s):2])
    odd = (s[1:len(s):2])
    if(len(even)!=len(odd)):
        even=even.replace(even[int(len(even)/2)],"") #If odd,replace middle character with ""
    if(even==odd):
        print("Magic string")
    else:
        print("Not a magic string")
    s=input("Enter String:-") #Input String

Enter String:-aabbcc
Magic string
Enter String:-abcabc
Not a magic string
Enter String:-aabcc
Magic string
Enter String:-aba
Not a magic string
Enter String:-aaaabbbbcccc
Magic string
Enter String:-stop
Not a magic string
Enter String:-Stop



```
A sports academy plans for a Badminton tournament. The
participants register their names and date of birth for the
tournament. The academy has to arrange the participants in three
different categories: under 10, under 13 and under 15. You have
to help the academy in maintaining the collection of name and
date of birth of participants and organize the team list. Draw the
PAC, pseudocode and develop the python code to get the details
of the participants till name is not equal to ‘stop’ and print a
consolidated team list with every item containing the number of
entries and names of the participants in sorted order under each
category.
Input format:
Enter the name
Enter the date of birth
…
stop
Output format:
A single list containing number of entries and sorted names of the
participants in under10,under13,under15 categories

```

**Input:**
```
name for name
dob for date of birth
a list in which value will stored 

```
**Logic**
```
while(name!="stop"):                      \\Continue Execution till user stop
  name=input("Enter name:-")
  if name=='stop':
    break
  dob=input("Enter DOB in DD-MM-YYYY Format:-")
  ag=2020-int(dob[6:])  \\age calculation of student by converting to int -2020 
  if(ag<10):             \\Compare age less than 10 
    a[0][1].append(name)
  elif ag<13:            \\Compare age less than 13 
    a[1][1].append(name)
  elif ag<15:            \\Compare age less than 15
    a[2][1].append(name)
a[0][0]=len(a[0][1])        \\Count Number of element
a[1][0]=len(a[1][1])
a[2][0]=len(a[2][1])  
```
**OUTPUT:-**
```
a final list
```

In [ ]:
'''
Test Cases Input:--
manish
08-10-2007
santhosh
12-12-2009
avinesh
06-12-2009
stop
Test Cases Expected Output [[0, []], [2, ['avinesh', 'santhosh']], [1, ['manish']]]
'''
name=''
a=[[0,[]],[0,[]],[0,[]]]
while(name!="stop"):
  name=input("Enter name:-")
  if name=='stop':
    break
  dob=input("Enter DOB in DD-MM-YYYY Format:-")
  ag=2020-int(dob[6:])
  if(ag<10):
    a[0][1].append(name)
  elif ag<13:
    a[1][1].append(name)
  elif ag<15:
    a[2][1].append(name)
a[0][0]=len(a[0][1])
a[1][0]=len(a[1][1])
a[2][0]=len(a[2][1])  
print(a)

Enter name:-manish
Enter DOB in DD-MM-YYYY Format:-08-10-2007
Enter name:-santosh
Enter DOB in DD-MM-YYYY Format:-12-12-2009
Enter name:-avinash
Enter DOB in DD-MM-YYYY Format:-06-12-2009
Enter name:-stop
[[0, []], [2, ['santosh', 'avinash']], [1, ['manish']]]

In [ ]:
'''
Test Cases Input
Babu
09-08-2007
Vivek
01-01-2012
arun
13-12-2006
Ashwin
18-05-2009
ashok
21-11-2011
guru
09-09-2009
stop
Test Cases Expected Output 
[[2, ['ashok', 'Vivek']], [2, ['Ashwin', 'guru']], [2,
['arun', 'Babu']]]
'''
name=''
a=[[0,[]],[0,[]],[0,[]]]
while(name!="stop"):
  name=input("Enter name:-")
  if name=='stop':
    break
  dob=input("Enter DOB in DD-MM-YYYY Format:-")
  ag=2020-int(dob[6:])
  if(ag<10):
    a[0][1].append(name)
  elif ag<13:
    a[1][1].append(name)
  elif ag<15:
    a[2][1].append(name)
a[0][0]=len(a[0][1])
a[1][0]=len(a[1][1])
a[2][0]=len(a[2][1])  
print(a)

Enter name:-Babu
Enter DOB in DD-MM-YYYY Format:-09-0892007
Enter name:-Vivek
Enter DOB in DD-MM-YYYY Format:-01-01-2012
Enter name:-arun
Enter DOB in DD-MM-YYYY Format:-13-12-2006
Enter name:-Ashwin
Enter DOB in DD-MM-YYYY Format:-18-05-2009
Enter name:-Ashok
Enter DOB in DD-MM-YYYY Format:-21-11-2011
Enter name:-guru
Enter DOB in DD-MM-YYYY Format:-09-09-2009
Enter name:-stop
[[2, ['Vivek', 'Ashok']], [2, ['Ashwin', 'guru']], [2, ['Babu', 'arun']]]

In [ ]:
'''
Test Cases Input stop
Test Cases Expected Output [[0, []], [0, []], [0, []]]
'''
name=''
a=[[0,[]],[0,[]],[0,[]]]
while(name!="stop"):
  name=input("Enter name:-")
  if name=='stop':
    break
  dob=input("Enter DOB in DD-MM-YYYY Format:-")
  ag=2020-int(dob[6:])
  if(ag<10):
    a[0][1].append(name)
  elif ag<13:
    a[1][1].append(name)
  elif ag<15:
    a[2][1].append(name)
a[0][0]=len(a[0][1])
a[1][0]=len(a[1][1])
a[2][0]=len(a[2][1])  
print(a)

Enter name:-stop
[[0, []], [0, []], [0, []]]

In [ ]:
'''
Test Cases Input
guna
10-10-2011
guna
10-10-2010
stop
Test Cases Expected Output [[2, ['guna', 'guna']], [0, []], [0, []]]'''
name=''
a=[[0,[]],[0,[]],[0,[]]]
while(name!="stop"):
  name=input("Enter name:-")
  if name=='stop':
    break
  dob=input("Enter DOB in DD-MM-YYYY Format:-")
  ag=2020-int(dob[6:])
  if(ag<=10):
    a[0][1].append(name)
  elif ag<=13:
    a[1][1].append(name)
  elif ag<=15:
    a[2][1].append(name)
a[0][0]=len(a[0][1])
a[1][0]=len(a[1][1])
a[2][0]=len(a[2][1])  
print(a)

Enter name:-guna
Enter DOB in DD-MM-YYYY Format:-10-10-2011
Enter name:-guna
Enter DOB in DD-MM-YYYY Format:-10-10-2010
Enter name:-stop
[[2, ['guna', 'guna']], [0, []], [0, []]]

```
A factory has ‘N’ employees working in it. Each employee has
an unique identification number (id). When they enter the
factory, their in_time is noted and when they leave the factory,
their out_time is noted. Both in_time and out_time of employees
can not be altered and in 24-hour format as hours:minutes. The
employees are paid hourly wages such that an employee gets Rs.
200/hour and Rs.3/minute if minutes>=30. Given the number of
employees, their id, in_time and out_time, develop an algorithm
and python code to print the id, in_time, out_time as strings and
wages for each employee with id as key and in_time, out_time
and wages as its value.
Note: use import pprint and pprint.pprint(variable) to print the
dictionary
Input format:
Enter the number of employees, N
Enter the id of 1st employee
Enter the in_time of 1st employee
Enter the out_time of 1st employee
…
Enter the id of nth employee
Enter the in_time of nth employee
Enter the out_time of nth employee
Output format:
print id as key and in_time, out_time, wages as values
```

**Input:-**
```
n //Number of Employees
id //Emp id
in_time //in_time of employee
out_time //out__time of employee
data // Dictionary for storing final outcome
```
**Logic**
```
for i in range(0,n):
  in_hr='' \\initialize variable
  in_min=''
  id=input('Enter the id of Employee:-')
  in_time=input('Enter the in_time of Employee:-')
  out_time=input('Enter the out_time of Employee:-')
  flag=0
  for i in in_time:
    if i==':':    //User may insert in 8:00 or 08:00 for getting appropriate i/p
      flag=1     //flag to difference between min & hr flag=0 for hr & 1 for min
    elif flag==0:
      in_hr+=i
    elif flag==1:
      in_min+=i
  in_hr=(int(in_hr)*60)+int(in_min)    //Convert in_hr into min
  out_hr=int(out_time[0:2])*60        //convert out_hr into min
  out_min=int(out_time[3:])       
  out_hr+=out_min
  hr=(out_hr-in_hr)//60              //convert to hour
  min=(out_hr-in_hr)%60              //convert to min
  if min>=30:                     //to calculate wage if min>30 based on hr&min
    wage=hr*200+min*3
  else:                           //calculate wage if min<30 based on hr only
    wage=hr*200
  lst[0]=in_time
  lst[1]=out_time
  lst[2]=wage                 // store all values in list lst
  t1=tuple(lst)              //store value of lst in tuple as tuple is immutable
  data[id]=t1                //insert data as key and value in dictionary data
  lst.clear                  //clear list for next iteration
  t1=tuple()                //to clear tuple
  s={k:data[k] for k in sorted(data)} //to sort element based on key in dict
```
**OUTPUT:-**
```
s //Sorted dictionary
```

In [42]:
'''
Test Cases Input
2
100
8:00
16:30
200
9:35
18:20
Test Cases Expected Output {'100': ('8:00', '16:30', 1690), '200': ('9:35', '18:20',
1735)}

'''
n=int(input("Enter the number of Employees:-"))
data={}
lst=['','','']
for i in range(0,n):
  in_hr=''
  in_min=''
  id=input('Enter the id of Employee:-')
  in_time=input('Enter the in_time of Employee:-')
  out_time=input('Enter the out_time of Employee:-')
  flag=0
  for i in in_time:
    if i==':':
      flag=1
    elif flag==0:
      in_hr+=i
    elif flag==1:
      in_min+=i
  in_hr=(int(in_hr)*60)+int(in_min)
  out_hr=int(out_time[0:2])*60
  out_min=int(out_time[3:])
  out_hr+=out_min
  hr=(out_hr-in_hr)//60
  min=(out_hr-in_hr)%60
  if min>=30:
    wage=hr*200+min*3
  else:
    wage=hr*200
  lst[0]=in_time
  lst[1]=out_time
  lst[2]=wage
  t1=tuple(lst)
  data[id]=t1
  lst.clear
  t1=tuple()
s={k:data[k] for k in sorted(data)}
print(s)

Enter the number of Employees:-2
Enter the id of Employee:-100
Enter the in_time of Employee:-8:00
Enter the out_time of Employee:-16:30
Enter the id of Employee:-200
Enter the in_time of Employee:-9:35
Enter the out_time of Employee:-18:20
{'100': ('8:00', '16:30', 1690), '200': ('9:35', '18:20', 1735)}

In [13]:
'''
Test Cases Input
3
111
08:30
14:00
113
09:30
19:30
112
08:00
11:59
Test Cases Expected Output
{'111': ('08:30', '14:00', 1090),
'112': ('08:00', '11:59', 777),
'113': ('09:30', '19:30', 2000)}
'''
n=int(input("Enter the number of Employees:-"))
data={}
lst=['','','']
for i in range(0,n):
  in_hr=''
  in_min=''
  id=input('Enter the id of Employee:-')
  in_time=input('Enter the in_time of Employee:-')
  out_time=input('Enter the out_time of Employee:-')
  flag=0
  for i in in_time:
    if i==':':
      flag=1
    elif flag==0:
      in_hr+=i
    elif flag==1:
      in_min+=i
  in_hr=(int(in_hr)*60)+int(in_min)
  out_hr=int(out_time[0:2])*60
  out_min=int(out_time[3:])
  out_hr+=out_min
  hr=(out_hr-in_hr)//60
  min=(out_hr-in_hr)%60
  if min>=30:
    wage=hr*200+min*3
  else:
    wage=hr*200
  lst[0]=in_time
  lst[1]=out_time
  lst[2]=wage
  t1=tuple(lst)
  data[id]=t1
  lst.clear
  t1=tuple()
s={k:data[k] for k in sorted(data)}
print(s)

Enter the number of Employees:-3
Enter the id of Employee:-111
Enter the in_time of Employee:-08:30
Enter the out_time of Employee:-14:00
Enter the id of Employee:-113
Enter the in_time of Employee:-09:30
Enter the out_time of Employee:-19:30
Enter the id of Employee:-112
Enter the in_time of Employee:-08:00
Enter the out_time of Employee:-11:59
{'111': ('08:30', '14:00', 1090), '112': ('08:00', '11:59', 777), '113': ('09:30', '19:30', 2000)}

In [14]:
'''
Hidden Test Cases Input
4
101
06:20
12:45
105
09:15
14:55
103
14:12
19:47
102
09:30
20:00
Hidden Test Cases Expected
Output
{'101': ('06:20', '12:45', 1200),
'102': ('09:30', '20:00', 2090),
'103': ('14:12', '19:47', 1105),
'105': ('09:15', '14:55', 1120)}
'''
n=int(input("Enter the number of Employees:-"))
data={}
lst=['','','']
for i in range(0,n):
  in_hr=''
  in_min=''
  id=input('Enter the id of Employee:-')
  in_time=input('Enter the in_time of Employee:-')
  out_time=input('Enter the out_time of Employee:-')
  flag=0
  for i in in_time:
    if i==':':
      flag=1
    elif flag==0:
      in_hr+=i
    elif flag==1:
      in_min+=i
  in_hr=(int(in_hr)*60)+int(in_min)
  out_hr=int(out_time[0:2])*60
  out_min=int(out_time[3:])
  out_hr+=out_min
  hr=(out_hr-in_hr)//60
  min=(out_hr-in_hr)%60
  if min>=30:
    wage=hr*200+min*3
  else:
    wage=hr*200
  lst[0]=in_time
  lst[1]=out_time
  lst[2]=wage
  t1=tuple(lst)
  data[id]=t1
  lst.clear
  t1=tuple()
s={k:data[k] for k in sorted(data)}
print(s)

Enter the number of Employees:-4
Enter the id of Employee:-101
Enter the in_time of Employee:-06:20
Enter the out_time of Employee:-12:45
Enter the id of Employee:-105
Enter the in_time of Employee:-09:15
Enter the out_time of Employee:-14:55
Enter the id of Employee:-103
Enter the in_time of Employee:-14:12
Enter the out_time of Employee:-19:47
Enter the id of Employee:-102
Enter the in_time of Employee:-09:30
Enter the out_time of Employee:-20:00
{'101': ('06:20', '12:45', 1200), '102': ('09:30', '20:00', 2090), '103': ('14:12', '19:47', 1105), '105': ('09:15', '14:55', 1120)}